name: Trigger Deployment

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
    paths:
      - 'charts/opentelemetry-demo/**'  # Only trigger when files in the 'charts/' directory are modified

jobs:
  notify_deployment_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Repo 1 to trigger deployment
        run: |
          curl -X POST https://api.github.com/repos/shreya13p/otel-ci-pipeline/dispatches \
            -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
            -d '{"event_type": "deploy_otel", "client_payload": {"message": "Triggered by chart changes"}}'
